//! The canonical mapping from an MCP tool name to the JSON Schema that
//! describes its `structuredContent`.
//!
//! Every advertised `outputSchema` is generated by `schemars` from the exact
//! serde struct the tool returns, so a field added to a result reaches the
//! advertised schema with no second list to update. This module holds the only
//! tool-name-to-schema mapping in the codebase;
//! `mcp_common::build_server_spec_with_hidden` is the only place that reads it.

use brokk_bifrost_analysis::blast_radius::{BlastRadiusResult, MissingTestsResult};
use brokk_bifrost_analysis::cyclomatic_complexity_diff::CyclomaticComplexityDiffResult;
use brokk_bifrost_analysis::searchtools::{
    ActiveWorkspaceResult, GetDefinitionResult, SearchSymbolsResult,
};
use brokk_bifrost_policy::BuiltInPolicyPackManifest;
use serde_json::Value;

type OutputSchemaSource = fn() -> Value;

const OUTPUT_SCHEMAS: &[(&str, OutputSchemaSource)] = &[
    ("blast_radius", generate_output_schema::<BlastRadiusResult>),
    (
        "cyclomatic_complexity",
        generate_output_schema::<CyclomaticComplexityDiffResult>,
    ),
    (
        "missing_tests",
        generate_output_schema::<MissingTestsResult>,
    ),
    (
        "get_active_workspace",
        generate_output_schema::<ActiveWorkspaceResult>,
    ),
    (
        "list_policies",
        generate_output_schema::<BuiltInPolicyPackManifest>,
    ),
    (
        "search_symbols",
        generate_output_schema::<SearchSymbolsResult>,
    ),
    (
        "get_definitions_by_location",
        generate_output_schema::<GetDefinitionResult>,
    ),
];

/// The advertised schema for `tool_name`, or `None` for a tool whose result
/// shape is not yet published.
pub(crate) fn output_schema_for(tool_name: &str) -> Option<Value> {
    OUTPUT_SCHEMAS
        .iter()
        .find(|(name, _)| *name == tool_name)
        .map(|(_, generate)| generate())
}

/// Generate under the *serialize* contract, not schemars' default deserialize
/// contract. An `outputSchema` describes what the server writes, and the two
/// contracts disagree on required-ness: under the deserialize contract a field
/// carrying `#[serde(skip_serializing_if = "Vec::is_empty")]` without a
/// `default` is marked required even though serialization omits it, which would
/// make real tool output fail validation against its own advertised schema.
/// The serialize contract derives required-ness from `skip_serializing_if`
/// alone, which is exactly what the wire does.
fn generate_output_schema<T: schemars::JsonSchema>() -> Value {
    let schema = schemars::generate::SchemaSettings::draft2020_12()
        .for_serialize()
        .into_generator()
        .into_root_schema_for::<T>();
    serde_json::to_value(schema).expect("a generated JSON Schema is serializable")
}

#[cfg(test)]
mod tests {
    use super::*;

    const JSON_SCHEMA_2020_12: &str = "https://json-schema.org/draft/2020-12/schema";

    #[test]
    fn every_registered_tool_yields_a_2020_12_schema() {
        for (name, _) in OUTPUT_SCHEMAS {
            let schema = output_schema_for(name)
                .unwrap_or_else(|| panic!("`{name}` is registered but resolved to no schema"));
            let object = schema
                .as_object()
                .unwrap_or_else(|| panic!("`{name}` produced a non-object schema: {schema}"));
            assert_eq!(
                object.get("$schema").and_then(Value::as_str),
                Some(JSON_SCHEMA_2020_12),
                "`{name}` schema does not declare the 2020-12 dialect: {schema}"
            );
        }
    }

    /// A field that serialization omits must not be advertised as required, or
    /// real tool output fails validation against its own schema. Schemars' own
    /// default (the deserialize contract) marks `bare_vec` required, which is
    /// why [`generate_output_schema`] selects the serialize contract.
    #[test]
    fn an_omitted_field_is_never_required() {
        // Never constructed: only its generated schema is inspected.
        #[allow(dead_code)]
        #[derive(schemars::JsonSchema)]
        struct SkipProbe {
            #[serde(skip_serializing_if = "Vec::is_empty")]
            bare_vec: Vec<String>,
            #[serde(skip_serializing_if = "Option::is_none")]
            bare_option: Option<String>,
        }

        assert_eq!(generate_output_schema::<SkipProbe>().get("required"), None);
    }

    #[test]
    fn an_unregistered_tool_has_no_schema() {
        assert!(output_schema_for("get_file_contents").is_none());
        assert!(output_schema_for("no_such_tool").is_none());
    }

    #[test]
    fn blast_radius_names_callable_test_evidence_as_context() {
        let schema = output_schema_for("blast_radius").expect("blast-radius schema");
        let analysis_properties = schema
            .pointer("/$defs/BlastRadiusAnalysis/properties")
            .and_then(Value::as_object)
            .unwrap_or_else(|| panic!("analysis properties missing: {schema}"));
        assert!(analysis_properties.contains_key("analyzer_changed_test_paths"));
        let properties = schema
            .pointer("/$defs/BlastRadiusCallableSymbol/properties")
            .and_then(Value::as_object)
            .unwrap_or_else(|| panic!("callable-symbol properties missing: {schema}"));
        assert!(properties.contains_key("in_test_context"));
        assert!(!properties.contains_key("is_test"));
    }

    /// A renamed or removed tool must not leave its schema stranded under the
    /// old name, where nothing would ever advertise it.
    #[test]
    fn every_registered_tool_exists_in_the_searchtools_registry() {
        let spec = crate::mcp_registry::resolve_server_spec("searchtools")
            .expect("the searchtools registry resolves");
        for (name, _) in OUTPUT_SCHEMAS {
            assert!(
                spec.tool_names.contains(*name),
                "`{name}` has an output schema but is not a searchtools tool: {:?}",
                spec.tool_names
            );
        }
    }
}
