//! Per-method counters on the reader seam.
//!
//! The reader seam is the pair of traits through which the language-neutral
//! evaluator reads facts: [`BatchResolutionFragmentSource`] (21 methods) and
//! [`SelectedTypedFactSource`] (39 methods). Nothing counted them. The counts
//! that existed were one layer down (interior indexes) or two layers down (SQL
//! statements), so "which question does a request ask most" could only be
//! answered by a proxy. This module answers it directly: for every one of the
//! sixty methods it records calls, keys requested and rows handed back, per
//! request and per process.
//!
//! The instrument is off unless `BIFROST_SEAM_PROFILE` names an output file.
//! The variable is read once per process. With it unset every counting site is
//! one `Option` test against a value the optimizer can hoist, and no request
//! observes any other difference.
//!
//! # Where the one counting point is
//!
//! Counting happens in [`SeamProfiled`], a forwarding decorator whose sixty
//! methods are generated by the macros below. It counts at the trait, not in
//! an implementor, so it survives milestone 6 replacing every implementor: the
//! only thing that moves is the single line that wraps a source.
//!
//! Operation factories borrow their existing lexical and typed SQL reader
//! handles through this decorator. The evaluator and demand builders use the
//! observed trait views; inherent metadata and context-token queries keep the
//! same raw handles. Internal SQL reader delegation remains inside the borrow,
//! so it neither creates a second cache nor counts a second seam call.
//!
//! # Rows
//!
//! A method that returns its rows is counted from what it returns. A method
//! that streams pages through a visitor is counted at the visitor:
//! [`TypedFactPageVisitor::count_rows_as`] tags the caller's visitor with the
//! method that is reading through it, and `visit_page` adds the page's length.
//! Wrapping the visitor in a second visitor was rejected: a visitor carries the
//! resolution session's scope-step charge, so a wrapper would charge the budget
//! twice and change what a request answers.
//!
//! # Output
//!
//! JSON lines. One `request` line per MCP tool call, carrying the tool name,
//! the wall time and that request's per-method deltas. One `totals` line every
//! [`TOTALS_INTERVAL`] and at the end of every request, so a process killed by
//! `timeout` (the warm `usage_graph` workload does not finish) still leaves its
//! counts behind. The digest reads the last `totals` line.

use std::io::Write;
use std::path::PathBuf;
use std::sync::atomic::{AtomicBool, AtomicU64, AtomicUsize, Ordering};
use std::sync::{Mutex, OnceLock};
use std::time::{Duration, Instant};

use brokk_bifrost_core::analyzer::usages::resolution_session::ResolutionSession;

use crate::CancellationToken;
use crate::analyzer::store::Result as StoreResult;
use crate::hash::HashSet;

use super::batch::{
    BatchCandidateCompletionOutcome, BatchCandidateMatch, BatchCandidateOutcome,
    BatchCandidateRequest, BatchDefinitionNode, BatchEndpointClassification,
    BatchResolutionFragmentSource, CandidatePathIdentity, ReferenceSeed, ReferenceSeedBatch,
    ReferenceSeedReadOutcome, ReverseCandidateGapExclusionPlan, ReverseReferenceSeedRequest,
};
use super::common_fact_lowering::LoweredDeferredMemberOwner;
use super::engine::ResolutionQuery;
use super::fact_source::{
    DeclarationAccessDecision, DeferredMemberOwnerLookupName, FactPageVisitor, FactReadOutcome,
    LoweredRustDeclarationAuthority, LoweredRustReferenceContext, QualifiedRouteSlotLookup,
    RustImplementedTraits, SelectedGapReasonProvenance, SelectedQualifiedRoute,
    SelectedTypeFrontierCompletion, SelectedTypedFactSource, SelectedTypedRow,
    TypedFactPageVisitor, TypedFactReadOutcome, TypedFactRequest,
};
use super::local_identity::SelectedResolutionMountOrdinal;
use super::model::{
    BindingFragmentId, BindingNodeId, PartialPath, ResolutionCompletion, SemanticId,
    TypeTransferRule,
};
use super::typed_fact_lowering::{
    LoweredBindingProjection, LoweredCallApplicabilityObligation, LoweredCallableSignatureProperty,
    LoweredConstructionRequirementProperty, LoweredDeclarationTypeProperty,
    LoweredDeclarationVisibilityProperty, LoweredDefinitionPropertyGap, LoweredIntrinsicSeed,
    LoweredMemberOwnerProperty, LoweredMemberScopeProperty, LoweredSupertypeProperty,
    LoweredTypeComponent, LoweredTypeTransfer, LoweredTypedFrontier, LoweredUnderlyingType,
};

/// Names the JSON-lines output file. Unset means no instrument at all.
pub const PROFILE_PATH_ENV: &str = "BIFROST_SEAM_PROFILE";

/// How often the background writer appends a `totals` line.
///
/// A one-shot corpus run is killed by `timeout` and never returns from `main`,
/// so the totals cannot be written only at exit.
const TOTALS_INTERVAL: Duration = Duration::from_secs(5);

macro_rules! seam_methods {
    ($($variant:ident => $name:literal, $owner:literal;)*) => {
        /// One method of one reader trait. The fixed-size counter table is
        /// indexed by this; nothing here grows with the workspace.
        #[derive(Clone, Copy, PartialEq, Eq, Debug)]
        #[repr(usize)]
        pub enum SeamMethod {
            $($variant,)*
        }

        impl SeamMethod {
            /// Every method of both traits, in declaration order.
            pub const ALL: &'static [Self] = &[$(Self::$variant,)*];

            /// The method's Rust name, which is what the digest reports.
            pub const fn as_str(self) -> &'static str {
                match self {
                    $(Self::$variant => $name,)*
                }
            }

            /// Which of the two traits declares it.
            pub const fn owner(self) -> &'static str {
                match self {
                    $(Self::$variant => $owner,)*
                }
            }
        }
    };
}

seam_methods! {
    SelectionAuthority => "selection_authority", "BatchResolutionFragmentSource";
    AdmitsReverseReference => "admits_reverse_reference", "BatchResolutionFragmentSource";
    ScopeReverseInventoryCompletion => "scope_reverse_inventory_completion", "BatchResolutionFragmentSource";
    GoLookupSpelling => "go_lookup_spelling", "BatchResolutionFragmentSource";
    InternSharedNameDigest => "intern_shared_name_digest", "BatchResolutionFragmentSource";
    SupportsGoUniverse => "supports_go_universe", "BatchResolutionFragmentSource";
    ReferenceSeed => "reference_seed", "BatchResolutionFragmentSource";
    LookupReferenceSeeds => "lookup_reference_seeds", "BatchResolutionFragmentSource";
    LookupDefinitionNode => "lookup_definition_node", "BatchResolutionFragmentSource";
    LookupDefinitionNodes => "lookup_definition_nodes", "BatchResolutionFragmentSource";
    IssueReverseReferenceSeeds => "issue_reverse_reference_seeds", "BatchResolutionFragmentSource";
    VisitReferenceSeedBatches => "visit_reference_seed_batches", "BatchResolutionFragmentSource";
    VisitReferenceSeedBatchesInFragments => "visit_reference_seed_batches_in_fragments", "BatchResolutionFragmentSource";
    ClassifyEndpointNodes => "classify_endpoint_nodes", "BatchResolutionFragmentSource";
    MatchForwardCandidates => "match_forward_candidates", "BatchResolutionFragmentSource";
    VisitForwardCandidateMatchPages => "visit_forward_candidate_match_pages", "BatchResolutionFragmentSource";
    VisitForwardRootCandidateMatchPages => "visit_forward_root_candidate_match_pages", "BatchResolutionFragmentSource";
    VisitForwardCandidateMatchPagesLimited => "visit_forward_candidate_match_pages_limited", "BatchResolutionFragmentSource";
    MatchReverseCandidates => "match_reverse_candidates", "BatchResolutionFragmentSource";
    VisitReverseCandidateMatchPages => "visit_reverse_candidate_match_pages", "BatchResolutionFragmentSource";
    VisitReverseRootCandidateMatchPages => "visit_reverse_root_candidate_match_pages", "BatchResolutionFragmentSource";
    VisitReverseCandidateMatchPagesWithGapExclusionsShared => "visit_reverse_candidate_match_pages_with_gap_exclusions_shared", "BatchResolutionFragmentSource";
    VisitReverseCandidateMatchPagesWithGapExclusions => "visit_reverse_candidate_match_pages_with_gap_exclusions", "BatchResolutionFragmentSource";
    HydrateCandidatePaths => "hydrate_candidate_paths", "BatchResolutionFragmentSource";
    VisitTypeTransferRules => "visit_type_transfer_rules", "BatchResolutionFragmentSource";
    RustCrateAccess => "rust_crate_access", "SelectedTypedFactSource";
    RustCrateSetAccess => "rust_crate_set_access", "SelectedTypedFactSource";
    RustTraitNameableAt => "rust_trait_nameable_at", "SelectedTypedFactSource";
    RustImplementedTraitsNameableAt => "rust_implemented_traits_nameable_at", "SelectedTypedFactSource";
    RustImplItemTraits => "rust_impl_item_traits", "SelectedTypedFactSource";
    SelectionHasJavaSemantics => "selection_has_java_semantics", "SelectedTypedFactSource";
    JavaAccessEndpoints => "java_access_endpoints", "SelectedTypedFactSource";
    GoCallableLookups => "go_callable_lookups", "SelectedTypedFactSource";
    GoMemberDeclarations => "go_member_declarations", "SelectedTypedFactSource";
    JavaInheritanceDeclarations => "java_inheritance_declarations", "SelectedTypedFactSource";
    RustSupertraitOwners => "rust_supertrait_owners", "SelectedTypedFactSource";
    RustExternalTypeIdentities => "rust_external_type_identities", "SelectedTypedFactSource";
    RustExternalTypeImportPath => "rust_external_type_import_path", "SelectedTypedFactSource";
    RustModuleDefinitions => "rust_module_definitions", "SelectedTypedFactSource";
    VisitSelectedFragmentPages => "visit_selected_fragment_pages", "SelectedTypedFactSource";
    ReadSelectedReverseInventoryCompletion => "read_selected_reverse_inventory_completion", "SelectedTypedFactSource";
    VisitRustReferenceContextPages => "visit_rust_reference_context_pages", "SelectedTypedFactSource";
    VisitRustDeclarationAuthorityPages => "visit_rust_declaration_authority_pages", "SelectedTypedFactSource";
    VisitTypedFrontierPages => "visit_typed_frontier_pages", "SelectedTypedFactSource";
    VisitTypeIdentityObservationPagesForReferences => "visit_type_identity_observation_pages_for_references", "SelectedTypedFactSource";
    VisitTypeFrontierCompletionPages => "visit_type_frontier_completion_pages", "SelectedTypedFactSource";
    VisitTypeTransferPagesFromSources => "visit_type_transfer_pages_from_sources", "SelectedTypedFactSource";
    VisitTypeTransferPagesToTargets => "visit_type_transfer_pages_to_targets", "SelectedTypedFactSource";
    VisitTypeComponentPagesForContainers => "visit_type_component_pages_for_containers", "SelectedTypedFactSource";
    VisitUnderlyingTypePagesForDefinitions => "visit_underlying_type_pages_for_definitions", "SelectedTypedFactSource";
    VisitIntrinsicSeedPagesForSlots => "visit_intrinsic_seed_pages_for_slots", "SelectedTypedFactSource";
    VisitIntrinsicSeedPagesForTypeIdentities => "visit_intrinsic_seed_pages_for_type_identities", "SelectedTypedFactSource";
    VisitBindingProjectionPagesForReferences => "visit_binding_projection_pages_for_references", "SelectedTypedFactSource";
    VisitBindingProjectionPagesForOutputs => "visit_binding_projection_pages_for_outputs", "SelectedTypedFactSource";
    VisitQualifiedRoutePagesForReferences => "visit_qualified_route_pages_for_references", "SelectedTypedFactSource";
    VisitQualifiedRoutePagesForSlotLookups => "visit_qualified_route_pages_for_slot_lookups", "SelectedTypedFactSource";
    VisitQualifiedRoutePagesForQualifierSlots => "visit_qualified_route_pages_for_qualifier_slots", "SelectedTypedFactSource";
    VisitQualifiedRoutePagesForLookups => "visit_qualified_route_pages_for_lookups", "SelectedTypedFactSource";
    VisitQualifiedRoutePagesForGapReasons => "visit_qualified_route_pages_for_gap_reasons", "SelectedTypedFactSource";
    VisitQualifiedRouteInventoryPages => "visit_qualified_route_inventory_pages", "SelectedTypedFactSource";
    VisitDeclarationTypePagesForDefinitions => "visit_declaration_type_pages_for_definitions", "SelectedTypedFactSource";
    VisitDeclarationTypePagesForSlots => "visit_declaration_type_pages_for_slots", "SelectedTypedFactSource";
    VisitDeclarationVisibilityPagesForDefinitions => "visit_declaration_visibility_pages_for_definitions", "SelectedTypedFactSource";
    VisitMemberScopePagesForDefinitions => "visit_member_scope_pages_for_definitions", "SelectedTypedFactSource";
    VisitMemberScopePagesForHeads => "visit_member_scope_pages_for_heads", "SelectedTypedFactSource";
    VisitMemberOwnerPagesForDefinitions => "visit_member_owner_pages_for_definitions", "SelectedTypedFactSource";
    VisitMemberOwnerPagesForOwners => "visit_member_owner_pages_for_owners", "SelectedTypedFactSource";
    VisitDeferredMemberOwnerPagesForDefinitions => "visit_deferred_member_owner_pages_for_definitions", "SelectedTypedFactSource";
    VisitDeferredMemberOwnerPagesForLookupNames => "visit_deferred_member_owner_pages_for_lookup_names", "SelectedTypedFactSource";
    VisitConstructionRequirementPagesForDefinitions => "visit_construction_requirement_pages_for_definitions", "SelectedTypedFactSource";
    VisitSupertypePagesForDefinitions => "visit_supertype_pages_for_definitions", "SelectedTypedFactSource";
    VisitSupertypePagesForReferences => "visit_supertype_pages_for_references", "SelectedTypedFactSource";
    VisitSupertypePagesForFrontiers => "visit_supertype_pages_for_frontiers", "SelectedTypedFactSource";
    HierarchyTerminalNodes => "hierarchy_terminal_nodes", "SelectedTypedFactSource";
    VisitDefinitionPropertyGapPagesForReasons => "visit_definition_property_gap_pages_for_reasons", "SelectedTypedFactSource";
    VisitDefinitionPropertyGapPagesForDefinitions => "visit_definition_property_gap_pages_for_definitions", "SelectedTypedFactSource";
    VisitCallApplicabilityPagesForCalleeReferences => "visit_call_applicability_pages_for_callee_references", "SelectedTypedFactSource";
    VisitCallApplicabilityPagesForGapReasons => "visit_call_applicability_pages_for_gap_reasons", "SelectedTypedFactSource";
    VisitCallableSignaturePagesForDefinitions => "visit_callable_signature_pages_for_definitions", "SelectedTypedFactSource";
    VisitGapReasonProvenancePagesForReasons => "visit_gap_reason_provenance_pages_for_reasons", "SelectedTypedFactSource";
}

/// The number of methods the two traits declare between them.
pub const METHOD_COUNT: usize = SeamMethod::ALL.len();

#[derive(Default)]
struct MethodCounters {
    calls: AtomicU64,
    keys: AtomicU64,
    rows: AtomicU64,
}

impl MethodCounters {
    fn snapshot(&self) -> (u64, u64, u64) {
        (
            self.calls.load(Ordering::Relaxed),
            self.keys.load(Ordering::Relaxed),
            self.rows.load(Ordering::Relaxed),
        )
    }
}

struct Profile {
    started: Instant,
    methods: [MethodCounters; METHOD_COUNT],
    output: Mutex<std::fs::File>,
    requests: AtomicU64,
    /// Nonzero while a request boundary is open. The per-request deltas are a
    /// difference of two process-wide snapshots, which is exact only while one
    /// request is open at a time; a line taken while this was above one says so.
    in_flight: AtomicUsize,
    dirty: AtomicBool,
}

impl Profile {
    fn open(path: &std::path::Path) -> Option<Self> {
        match std::fs::File::create(path) {
            Ok(output) => Some(Self {
                started: Instant::now(),
                methods: std::array::from_fn(|_| MethodCounters::default()),
                output: Mutex::new(output),
                requests: AtomicU64::new(0),
                in_flight: AtomicUsize::new(0),
                dirty: AtomicBool::new(true),
            }),
            Err(error) => {
                eprintln!(
                    "Bifrost seam profile could not create {}: {error}",
                    path.display()
                );
                None
            }
        }
    }

    fn snapshot(&self) -> Vec<(u64, u64, u64)> {
        self.methods.iter().map(MethodCounters::snapshot).collect()
    }

    fn write_line(&self, line: &str) {
        let mut output = self.output.lock().expect("seam profile output poisoned");
        if let Err(error) = writeln!(output, "{line}").and_then(|()| output.flush()) {
            eprintln!("Bifrost seam profile could not write a line: {error}");
        }
    }
}

static PROFILE: OnceLock<Option<Profile>> = OnceLock::new();

/// The process's profile, or `None` when [`PROFILE_PATH_ENV`] is unset. The
/// environment is read exactly once, on the first seam call or request scope.
fn profile() -> Option<&'static Profile> {
    PROFILE
        .get_or_init(|| {
            let path = PathBuf::from(std::env::var_os(PROFILE_PATH_ENV)?);
            let profile = Profile::open(&path)?;
            profile.write_line(&header_line());
            spawn_totals_writer();
            Some(profile)
        })
        .as_ref()
}

/// Whether the instrument is on in this process.
pub fn enabled() -> bool {
    profile().is_some()
}

fn header_line() -> String {
    let methods = SeamMethod::ALL
        .iter()
        .map(|method| serde_json::json!({"method": method.as_str(), "trait": method.owner()}))
        .collect::<Vec<_>>();
    serde_json::json!({
        "kind": "header",
        "pid": std::process::id(),
        "method_count": METHOD_COUNT,
        "totals_interval_ms": TOTALS_INTERVAL.as_millis(),
        "methods": methods,
    })
    .to_string()
}

fn spawn_totals_writer() {
    let spawned = std::thread::Builder::new()
        .name("bifrost-seam-profile".to_string())
        .spawn(|| {
            loop {
                std::thread::sleep(TOTALS_INTERVAL);
                write_totals();
            }
        });
    if let Err(error) = spawned {
        eprintln!("Bifrost seam profile has no background writer: {error}");
    }
}

/// Append a `totals` line now. With the variable unset it does nothing.
pub fn write_totals() {
    let Some(profile) = profile() else {
        return;
    };
    if !profile.dirty.swap(false, Ordering::Relaxed) {
        return;
    }
    let counters = profile.snapshot();
    let line = serde_json::json!({
        "kind": "totals",
        "uptime_ms": profile.started.elapsed().as_millis(),
        "requests": profile.requests.load(Ordering::Relaxed),
        "methods": method_object(&counters, None),
    })
    .to_string();
    profile.write_line(&line);
}

/// Every method whose call count moved, as `{name: {calls, keys, rows}}`.
fn method_object(now: &[(u64, u64, u64)], before: Option<&[(u64, u64, u64)]>) -> serde_json::Value {
    let mut object = serde_json::Map::new();
    for (index, method) in SeamMethod::ALL.iter().enumerate() {
        let (calls, keys, rows) = now[index];
        let (calls, keys, rows) = match before {
            Some(before) => (
                calls - before[index].0,
                keys - before[index].1,
                rows - before[index].2,
            ),
            None => (calls, keys, rows),
        };
        if calls == 0 {
            continue;
        }
        object.insert(
            method.as_str().to_string(),
            serde_json::json!({"calls": calls, "keys": keys, "rows": rows}),
        );
    }
    serde_json::Value::Object(object)
}

fn record_call(method: SeamMethod, keys: usize) {
    let Some(profile) = profile() else {
        return;
    };
    let counters = &profile.methods[method as usize];
    counters.calls.fetch_add(1, Ordering::Relaxed);
    counters.keys.fetch_add(keys as u64, Ordering::Relaxed);
    profile.dirty.store(true, Ordering::Relaxed);
}

/// Add rows handed to the caller. Called from the return of a method that
/// returns its rows, and from [`TypedFactPageVisitor::visit_page`] for a
/// method that streams them.
pub(super) fn record_rows(method: SeamMethod, rows: usize) {
    let Some(profile) = profile() else {
        return;
    };
    profile.methods[method as usize]
        .rows
        .fetch_add(rows as u64, Ordering::Relaxed);
}

/// One request boundary. Its `Drop` writes the request's line.
///
/// It is a scope and not a pair of calls so that an early return, a `?` or a
/// panic in the tool still closes the request.
pub struct RequestScope {
    inner: Option<OpenRequest>,
}

struct OpenRequest {
    tool: String,
    started: Instant,
    before: Vec<(u64, u64, u64)>,
    sql_before: Option<(u64, u128)>,
    overlapped: bool,
}

/// Open a request boundary for one MCP tool call. A no-op when the instrument
/// is off.
pub fn request_scope(tool: &str) -> RequestScope {
    let Some(profile) = profile() else {
        return RequestScope { inner: None };
    };
    let overlapped = profile.in_flight.fetch_add(1, Ordering::Relaxed) > 0;
    RequestScope {
        inner: Some(OpenRequest {
            tool: tool.to_string(),
            started: Instant::now(),
            before: profile.snapshot(),
            sql_before: brokk_bifrost_core::cache_db::sql_profile::totals(),
            overlapped,
        }),
    }
}

impl Drop for RequestScope {
    fn drop(&mut self) {
        let Some(open) = self.inner.take() else {
            return;
        };
        let profile = profile().expect("an open request scope implies a profile");
        let overlapped = open.overlapped || profile.in_flight.fetch_sub(1, Ordering::Relaxed) > 1;
        let now = profile.snapshot();
        profile.requests.fetch_add(1, Ordering::Relaxed);
        let mut line = serde_json::json!({
            "kind": "request",
            "tool": open.tool,
            "wall_ms": open.started.elapsed().as_secs_f64() * 1000.0,
            "overlapped": overlapped,
            "methods": method_object(&now, Some(&open.before)),
        });
        if let (Some((executions, nanos)), Some((before_executions, before_nanos))) = (
            brokk_bifrost_core::cache_db::sql_profile::totals(),
            open.sql_before,
        ) {
            line["sql"] = serde_json::json!({
                "executions": executions - before_executions,
                "nanos": (nanos - before_nanos).to_string(),
            });
        }
        profile.write_line(&line.to_string());
        write_totals();
    }
}

/// One counted reader source.
///
/// Every method forwards to `inner` and records one call, the keys the call
/// asked for (a batch's length, or one for a scalar question) and the rows the
/// call handed back. This is a shared view: the mutable exclusion entrypoint
/// forwards to the inner shared entrypoint, as the shared engine adapter does.
pub struct SeamProfiled<'a, T: ?Sized> {
    inner: &'a T,
}

impl<'a, T: ?Sized> SeamProfiled<'a, T> {
    pub(crate) const fn observing(inner: &'a T) -> Self {
        Self { inner }
    }
}

/// A method whose keys and rows are both known from its arguments and its
/// return value.
macro_rules! counted {
    ($method:ident ( $($argument:ident : $type:ty),* $(,)? ) -> $return:ty,
     $variant:ident, keys = $keys:expr, rows = |$result:ident| $rows:expr) => {
        fn $method(&self, $($argument: $type),*) -> $return {
            record_call(SeamMethod::$variant, $keys);
            let outcome = self.inner.$method($($argument),*);
            if let Ok($result) = &outcome {
                record_rows(SeamMethod::$variant, $rows);
            }
            outcome
        }
    };
}

/// A method that streams `&[BatchCandidateMatch]` pages through a closure.
macro_rules! counted_candidate_pages {
    ($method:ident, $variant:ident $(, $extra:ident : $extra_type:ty)*) => {
        fn $method(
            &self,
            requests: &[BatchCandidateRequest],
            $($extra: $extra_type,)*
            cancellation: &CancellationToken,
            visitor: &mut dyn FnMut(&[BatchCandidateMatch]) -> StoreResult<bool>,
        ) -> StoreResult<BatchCandidateCompletionOutcome> {
            record_call(SeamMethod::$variant, requests.len());
            let mut counting = |page: &[BatchCandidateMatch]| {
                record_rows(SeamMethod::$variant, page.len());
                visitor(page)
            };
            self.inner.$method(requests, $($extra,)* cancellation, &mut counting)
        }
    };
}

impl<T: ?Sized> BatchResolutionFragmentSource for SeamProfiled<'_, T>
where
    T: BatchResolutionFragmentSource,
{
    /// Counted like every other method of the seam, with the caveat that this
    /// one issues no source read: its calls say how often a caller asked which
    /// selection is answering, and its rows say how often one could be named.
    fn selection_authority(&self) -> Option<super::batch::SeedReadAuthority> {
        record_call(SeamMethod::SelectionAuthority, 0);
        let authority = self.inner.selection_authority();
        record_rows(
            SeamMethod::SelectionAuthority,
            usize::from(authority.is_some()),
        );
        authority
    }

    fn admits_reverse_reference(&self, reference: SemanticId) -> bool {
        record_call(SeamMethod::AdmitsReverseReference, 1);
        record_rows(SeamMethod::AdmitsReverseReference, 1);
        self.inner.admits_reverse_reference(reference)
    }

    fn scope_reverse_inventory_completion(
        &self,
        completion: &ResolutionCompletion,
    ) -> ResolutionCompletion {
        record_call(SeamMethod::ScopeReverseInventoryCompletion, 1);
        record_rows(SeamMethod::ScopeReverseInventoryCompletion, 1);
        self.inner.scope_reverse_inventory_completion(completion)
    }

    fn go_lookup_spelling(
        &self,
        reference: SemanticId,
        namespace: brokk_bifrost_core::analyzer::resolution_facts::ResolutionNamespace,
        cancellation: &CancellationToken,
    ) -> StoreResult<Option<String>> {
        record_call(SeamMethod::GoLookupSpelling, 1);
        let spelling = self
            .inner
            .go_lookup_spelling(reference, namespace, cancellation)?;
        record_rows(
            SeamMethod::GoLookupSpelling,
            usize::from(spelling.is_some()),
        );
        Ok(spelling)
    }

    fn intern_shared_name_digest(
        &self,
        digest: [u8; 32],
        cancellation: &CancellationToken,
    ) -> StoreResult<Option<SemanticId>> {
        record_call(SeamMethod::InternSharedNameDigest, 1);
        let name = self.inner.intern_shared_name_digest(digest, cancellation)?;
        record_rows(
            SeamMethod::InternSharedNameDigest,
            usize::from(name.is_some()),
        );
        Ok(name)
    }

    fn supports_go_universe(&self) -> bool {
        record_call(SeamMethod::SupportsGoUniverse, 0);
        record_rows(SeamMethod::SupportsGoUniverse, 1);
        self.inner.supports_go_universe()
    }

    counted!(
        reference_seed(query: ResolutionQuery, cancellation: &CancellationToken)
            -> StoreResult<Option<ReferenceSeed>>,
        ReferenceSeed,
        keys = 1,
        rows = |seed| usize::from(seed.is_some())
    );

    counted!(
        lookup_reference_seeds(queries: &[ResolutionQuery], cancellation: &CancellationToken)
            -> StoreResult<ReferenceSeedReadOutcome>,
        LookupReferenceSeeds,
        keys = queries.len(),
        rows = |outcome| outcome.rows().len()
    );

    counted!(
        lookup_definition_node(definition: SemanticId, cancellation: &CancellationToken)
            -> StoreResult<Option<BindingNodeId>>,
        LookupDefinitionNode,
        keys = 1,
        rows = |node| usize::from(node.is_some())
    );

    counted!(
        lookup_definition_nodes(definitions: &[SemanticId], cancellation: &CancellationToken)
            -> StoreResult<Vec<BatchDefinitionNode>>,
        LookupDefinitionNodes,
        keys = definitions.len(),
        rows = |nodes| nodes.len()
    );

    counted!(
        issue_reverse_reference_seeds(
            requests: &[ReverseReferenceSeedRequest],
            cancellation: &CancellationToken,
        ) -> StoreResult<Vec<ReferenceSeed>>,
        IssueReverseReferenceSeeds,
        keys = requests.len(),
        rows = |seeds| seeds.len()
    );

    fn visit_reference_seed_batches(
        &self,
        maximum_batch_size: usize,
        cancellation: &CancellationToken,
        visitor: &mut dyn FnMut(&ReferenceSeedBatch) -> StoreResult<bool>,
    ) -> StoreResult<ResolutionCompletion> {
        record_call(SeamMethod::VisitReferenceSeedBatches, 1);
        let mut counting = |batch: &ReferenceSeedBatch| {
            record_rows(SeamMethod::VisitReferenceSeedBatches, batch.len());
            visitor(batch)
        };
        self.inner
            .visit_reference_seed_batches(maximum_batch_size, cancellation, &mut counting)
    }

    fn visit_reference_seed_batches_in_fragments(
        &self,
        fragments: &HashSet<BindingFragmentId>,
        maximum_batch_size: usize,
        cancellation: &CancellationToken,
        visitor: &mut dyn FnMut(&ReferenceSeedBatch) -> StoreResult<bool>,
    ) -> StoreResult<ResolutionCompletion> {
        record_call(
            SeamMethod::VisitReferenceSeedBatchesInFragments,
            fragments.len(),
        );
        let mut counting = |batch: &ReferenceSeedBatch| {
            record_rows(
                SeamMethod::VisitReferenceSeedBatchesInFragments,
                batch.len(),
            );
            visitor(batch)
        };
        self.inner.visit_reference_seed_batches_in_fragments(
            fragments,
            maximum_batch_size,
            cancellation,
            &mut counting,
        )
    }

    counted!(
        classify_endpoint_nodes(nodes: &[BindingNodeId], cancellation: &CancellationToken)
            -> StoreResult<Vec<BatchEndpointClassification>>,
        ClassifyEndpointNodes,
        keys = nodes.len(),
        rows = |rows| rows.len()
    );

    counted!(
        match_forward_candidates(
            requests: &[BatchCandidateRequest],
            cancellation: &CancellationToken,
        ) -> StoreResult<BatchCandidateOutcome>,
        MatchForwardCandidates,
        keys = requests.len(),
        rows = |outcome| outcome.matches().len()
    );

    counted_candidate_pages!(
        visit_forward_candidate_match_pages,
        VisitForwardCandidateMatchPages
    );

    counted_candidate_pages!(
        visit_forward_root_candidate_match_pages,
        VisitForwardRootCandidateMatchPages,
        mounts: Option<&[SelectedResolutionMountOrdinal]>
    );

    counted_candidate_pages!(
        visit_forward_candidate_match_pages_limited,
        VisitForwardCandidateMatchPagesLimited,
        maximum_page_rows: usize,
        resolution_session: Option<&ResolutionSession>
    );

    counted!(
        match_reverse_candidates(
            requests: &[BatchCandidateRequest],
            cancellation: &CancellationToken,
        ) -> StoreResult<BatchCandidateOutcome>,
        MatchReverseCandidates,
        keys = requests.len(),
        rows = |outcome| outcome.matches().len()
    );

    counted_candidate_pages!(
        visit_reverse_candidate_match_pages,
        VisitReverseCandidateMatchPages
    );

    counted_candidate_pages!(
        visit_reverse_root_candidate_match_pages,
        VisitReverseRootCandidateMatchPages,
        mounts: Option<&[SelectedResolutionMountOrdinal]>
    );

    fn visit_reverse_candidate_match_pages_with_gap_exclusions_shared(
        &self,
        requests: &[BatchCandidateRequest],
        exclusions: &mut ReverseCandidateGapExclusionPlan,
        cancellation: &CancellationToken,
        visitor: &mut dyn FnMut(&[BatchCandidateMatch]) -> StoreResult<bool>,
    ) -> StoreResult<BatchCandidateCompletionOutcome> {
        const METHOD: SeamMethod =
            SeamMethod::VisitReverseCandidateMatchPagesWithGapExclusionsShared;
        record_call(METHOD, requests.len());
        let mut counting = |page: &[BatchCandidateMatch]| {
            record_rows(METHOD, page.len());
            visitor(page)
        };
        self.inner
            .visit_reverse_candidate_match_pages_with_gap_exclusions_shared(
                requests,
                exclusions,
                cancellation,
                &mut counting,
            )
    }

    fn visit_reverse_candidate_match_pages_with_gap_exclusions(
        &mut self,
        requests: &[BatchCandidateRequest],
        exclusions: &mut ReverseCandidateGapExclusionPlan,
        cancellation: &CancellationToken,
        visitor: &mut dyn FnMut(&[BatchCandidateMatch]) -> StoreResult<bool>,
    ) -> StoreResult<BatchCandidateCompletionOutcome> {
        const METHOD: SeamMethod = SeamMethod::VisitReverseCandidateMatchPagesWithGapExclusions;
        record_call(METHOD, requests.len());
        let mut counting = |page: &[BatchCandidateMatch]| {
            record_rows(METHOD, page.len());
            visitor(page)
        };
        self.inner
            .visit_reverse_candidate_match_pages_with_gap_exclusions_shared(
                requests,
                exclusions,
                cancellation,
                &mut counting,
            )
    }

    counted!(
        hydrate_candidate_paths(
            candidates: &[CandidatePathIdentity],
            cancellation: &CancellationToken,
        ) -> StoreResult<Vec<(CandidatePathIdentity, PartialPath)>>,
        HydrateCandidatePaths,
        keys = candidates.len(),
        rows = |paths| paths.len()
    );

    fn visit_type_transfer_rules(
        &self,
        source_slot: SemanticId,
        cancellation: &CancellationToken,
        visitor: &mut dyn FnMut(&TypeTransferRule) -> StoreResult<bool>,
    ) -> StoreResult<ResolutionCompletion> {
        record_call(SeamMethod::VisitTypeTransferRules, 1);
        let mut counting = |rule: &TypeTransferRule| {
            record_rows(SeamMethod::VisitTypeTransferRules, 1);
            visitor(rule)
        };
        self.inner
            .visit_type_transfer_rules(source_slot, cancellation, &mut counting)
    }
}

/// A typed read keyed on a request batch, streaming rows through the caller's
/// page visitor. Thirty-four of the thirty-nine typed methods are this shape.
macro_rules! counted_typed_pages {
    ($method:ident, $variant:ident, $key:ty, $row:ty) => {
        fn $method(
            &self,
            request: TypedFactRequest<'_, $key>,
            cancellation: &CancellationToken,
            visitor: &mut TypedFactPageVisitor<'_, $row>,
        ) -> StoreResult<TypedFactReadOutcome> {
            record_call(SeamMethod::$variant, request.len());
            visitor.count_rows_as(Some(SeamMethod::$variant));
            let outcome = self.inner.$method(request, cancellation, visitor);
            visitor.count_rows_as(None);
            outcome
        }
    };
}

/// A typed read with no request key: the question is the whole selection.
macro_rules! counted_typed_inventory {
    ($method:ident, $variant:ident, $row:ty) => {
        fn $method(
            &self,
            cancellation: &CancellationToken,
            visitor: &mut TypedFactPageVisitor<'_, $row>,
        ) -> StoreResult<TypedFactReadOutcome> {
            record_call(SeamMethod::$variant, 1);
            visitor.count_rows_as(Some(SeamMethod::$variant));
            let outcome = self.inner.$method(cancellation, visitor);
            visitor.count_rows_as(None);
            outcome
        }
    };
}

impl<T: ?Sized> SelectedTypedFactSource for SeamProfiled<'_, T>
where
    T: SelectedTypedFactSource,
{
    fn rust_crate_access(
        &self,
        crate_key: [u8; 32],
        base_blobs: &[(BindingFragmentId, i64)],
        reference: Option<&SelectedTypedRow<LoweredRustReferenceContext>>,
        definition: Option<&SelectedTypedRow<LoweredRustDeclarationAuthority>>,
    ) -> StoreResult<Option<DeclarationAccessDecision>> {
        record_call(SeamMethod::RustCrateAccess, 1);
        let outcome = self
            .inner
            .rust_crate_access(crate_key, base_blobs, reference, definition);
        if let Ok(decision) = &outcome {
            record_rows(SeamMethod::RustCrateAccess, usize::from(decision.is_some()));
        }
        outcome
    }

    fn rust_crate_set_access(
        &self,
        crate_key: [u8; 32],
        base_blobs: &[(BindingFragmentId, i64)],
        reference: Option<&SelectedTypedRow<LoweredRustReferenceContext>>,
        definition: Option<&SelectedTypedRow<LoweredRustDeclarationAuthority>>,
    ) -> StoreResult<Option<DeclarationAccessDecision>> {
        record_call(SeamMethod::RustCrateSetAccess, 1);
        let outcome = self
            .inner
            .rust_crate_set_access(crate_key, base_blobs, reference, definition);
        if let Ok(decision) = &outcome {
            record_rows(
                SeamMethod::RustCrateSetAccess,
                usize::from(decision.is_some()),
            );
        }
        outcome
    }

    fn rust_module_definitions(
        &self,
        definitions: &[SemanticId],
        cancellation: &CancellationToken,
    ) -> StoreResult<Vec<SemanticId>> {
        record_call(SeamMethod::RustModuleDefinitions, definitions.len());
        let outcome = self
            .inner
            .rust_module_definitions(definitions, cancellation);
        if let Ok(modules) = &outcome {
            record_rows(SeamMethod::RustModuleDefinitions, modules.len());
        }
        outcome
    }

    fn rust_implemented_traits_nameable_at(
        &self,
        owner: SemanticId,
        reference: SemanticId,
        cancellation: &CancellationToken,
    ) -> StoreResult<RustImplementedTraits> {
        record_call(SeamMethod::RustImplementedTraitsNameableAt, 1);
        let outcome =
            self.inner
                .rust_implemented_traits_nameable_at(owner, reference, cancellation);
        if let Ok(RustImplementedTraits::Traits(traits)) = &outcome {
            record_rows(SeamMethod::RustImplementedTraitsNameableAt, traits.len());
        }
        outcome
    }

    /// Whether the reference can name this specific Rust trait, independent of its implementor.
    fn rust_trait_nameable_at(
        &self,
        owner: SemanticId,
        reference: SemanticId,
        cancellation: &CancellationToken,
    ) -> StoreResult<RustImplementedTraits> {
        record_call(SeamMethod::RustTraitNameableAt, 1);
        let outcome = self
            .inner
            .rust_trait_nameable_at(owner, reference, cancellation);
        if let Ok(RustImplementedTraits::Traits(traits)) = &outcome {
            record_rows(SeamMethod::RustTraitNameableAt, traits.len());
        }
        outcome
    }

    fn rust_impl_item_traits(
        &self,
        member: SemanticId,
        cancellation: &CancellationToken,
    ) -> StoreResult<RustImplementedTraits> {
        record_call(SeamMethod::RustImplItemTraits, 1);
        let outcome = self.inner.rust_impl_item_traits(member, cancellation);
        if let Ok(RustImplementedTraits::Traits(traits)) = &outcome {
            record_rows(SeamMethod::RustImplItemTraits, traits.len());
        }
        outcome
    }

    fn selection_has_java_semantics(&self) -> bool {
        record_call(SeamMethod::SelectionHasJavaSemantics, 0);
        self.inner.selection_has_java_semantics()
    }

    fn java_access_endpoints(
        &self,
        semantics: &[SemanticId],
        cancellation: &CancellationToken,
    ) -> StoreResult<Option<Vec<super::fact_source::JavaAccessEndpoint>>> {
        record_call(SeamMethod::JavaAccessEndpoints, semantics.len());
        let outcome = self.inner.java_access_endpoints(semantics, cancellation);
        if let Ok(Some(rows)) = &outcome {
            record_rows(SeamMethod::JavaAccessEndpoints, rows.len());
        }
        outcome
    }

    fn go_callable_lookups(
        &self,
        lookups: &[(BindingFragmentId, SemanticId)],
        cancellation: &CancellationToken,
    ) -> StoreResult<Option<Vec<(SemanticId, SemanticId)>>> {
        record_call(SeamMethod::GoCallableLookups, lookups.len());
        let outcome = self.inner.go_callable_lookups(lookups, cancellation);
        if let Ok(Some(rows)) = &outcome {
            record_rows(SeamMethod::GoCallableLookups, rows.len());
        }
        outcome
    }

    fn go_member_declarations(
        &self,
        definitions: &[SemanticId],
        cancellation: &CancellationToken,
    ) -> StoreResult<Option<Vec<super::fact_source::GoMemberDeclaration>>> {
        record_call(SeamMethod::GoMemberDeclarations, definitions.len());
        let outcome = self.inner.go_member_declarations(definitions, cancellation);
        if let Ok(Some(rows)) = &outcome {
            record_rows(SeamMethod::GoMemberDeclarations, rows.len());
        }
        outcome
    }

    fn hierarchy_terminal_nodes(
        &self,
        gaps: &[SelectedGapReasonProvenance],
        cancellation: &CancellationToken,
    ) -> StoreResult<Option<Vec<(SemanticId, BindingNodeId)>>> {
        record_call(SeamMethod::HierarchyTerminalNodes, gaps.len());
        let outcome = self.inner.hierarchy_terminal_nodes(gaps, cancellation);
        if let Ok(Some(rows)) = &outcome {
            record_rows(SeamMethod::HierarchyTerminalNodes, rows.len());
        }
        outcome
    }

    fn java_inheritance_declarations(
        &self,
        definitions: &[SemanticId],
        cancellation: &CancellationToken,
    ) -> StoreResult<Option<Vec<super::fact_source::JavaInheritanceDeclaration>>> {
        record_call(SeamMethod::JavaInheritanceDeclarations, definitions.len());
        let outcome = self
            .inner
            .java_inheritance_declarations(definitions, cancellation);
        if let Ok(Some(rows)) = &outcome {
            record_rows(SeamMethod::JavaInheritanceDeclarations, rows.len());
        }
        outcome
    }

    fn rust_supertrait_owners(
        &self,
        owners: &[SemanticId],
        cancellation: &CancellationToken,
    ) -> StoreResult<Option<Vec<SemanticId>>> {
        record_call(SeamMethod::RustSupertraitOwners, owners.len());
        let outcome = self.inner.rust_supertrait_owners(owners, cancellation);
        if let Ok(Some(owners)) = &outcome {
            record_rows(SeamMethod::RustSupertraitOwners, owners.len());
        }
        outcome
    }

    fn rust_external_type_identities(
        &self,
        boundary: SemanticId,
        cancellation: &CancellationToken,
    ) -> StoreResult<Option<Vec<SemanticId>>> {
        record_call(SeamMethod::RustExternalTypeIdentities, 1);
        let outcome = self
            .inner
            .rust_external_type_identities(boundary, cancellation);
        if let Ok(Some(items)) = &outcome {
            record_rows(SeamMethod::RustExternalTypeIdentities, items.len());
        }
        outcome
    }

    fn rust_external_type_import_path(
        &self,
        boundary: SemanticId,
        cancellation: &CancellationToken,
    ) -> StoreResult<Option<Vec<String>>> {
        record_call(SeamMethod::RustExternalTypeImportPath, 1);
        let outcome = self
            .inner
            .rust_external_type_import_path(boundary, cancellation);
        if let Ok(Some(path)) = &outcome {
            record_rows(SeamMethod::RustExternalTypeImportPath, path.len());
        }
        outcome
    }

    fn visit_selected_fragment_pages(
        &self,
        cancellation: &CancellationToken,
        visitor: &mut FactPageVisitor<'_, BindingFragmentId>,
    ) -> StoreResult<FactReadOutcome> {
        record_call(SeamMethod::VisitSelectedFragmentPages, 1);
        visitor.count_rows_as(Some(SeamMethod::VisitSelectedFragmentPages));
        let outcome = self
            .inner
            .visit_selected_fragment_pages(cancellation, visitor);
        visitor.count_rows_as(None);
        outcome
    }

    fn read_selected_reverse_inventory_completion(
        &self,
        cancellation: &CancellationToken,
    ) -> StoreResult<TypedFactReadOutcome> {
        record_call(SeamMethod::ReadSelectedReverseInventoryCompletion, 1);
        record_rows(SeamMethod::ReadSelectedReverseInventoryCompletion, 1);
        self.inner
            .read_selected_reverse_inventory_completion(cancellation)
    }

    counted_typed_pages!(
        visit_rust_reference_context_pages,
        VisitRustReferenceContextPages,
        SemanticId,
        SelectedTypedRow<LoweredRustReferenceContext>
    );
    counted_typed_pages!(
        visit_rust_declaration_authority_pages,
        VisitRustDeclarationAuthorityPages,
        SemanticId,
        SelectedTypedRow<LoweredRustDeclarationAuthority>
    );
    counted_typed_pages!(
        visit_typed_frontier_pages,
        VisitTypedFrontierPages,
        SemanticId,
        SelectedTypedRow<LoweredTypedFrontier>
    );
    counted_typed_pages!(
        visit_type_identity_observation_pages_for_references,
        VisitTypeIdentityObservationPagesForReferences,
        SemanticId,
        SelectedTypedRow<LoweredTypedFrontier>
    );
    counted_typed_pages!(
        visit_type_frontier_completion_pages,
        VisitTypeFrontierCompletionPages,
        SemanticId,
        SelectedTypeFrontierCompletion
    );
    counted_typed_pages!(
        visit_type_transfer_pages_from_sources,
        VisitTypeTransferPagesFromSources,
        SemanticId,
        SelectedTypedRow<LoweredTypeTransfer>
    );
    counted_typed_pages!(
        visit_type_transfer_pages_to_targets,
        VisitTypeTransferPagesToTargets,
        SemanticId,
        SelectedTypedRow<LoweredTypeTransfer>
    );
    counted_typed_pages!(
        visit_type_component_pages_for_containers,
        VisitTypeComponentPagesForContainers,
        SemanticId,
        SelectedTypedRow<LoweredTypeComponent>
    );
    counted_typed_pages!(
        visit_underlying_type_pages_for_definitions,
        VisitUnderlyingTypePagesForDefinitions,
        SemanticId,
        SelectedTypedRow<LoweredUnderlyingType>
    );
    counted_typed_pages!(
        visit_intrinsic_seed_pages_for_slots,
        VisitIntrinsicSeedPagesForSlots,
        SemanticId,
        SelectedTypedRow<LoweredIntrinsicSeed>
    );
    counted_typed_pages!(
        visit_intrinsic_seed_pages_for_type_identities,
        VisitIntrinsicSeedPagesForTypeIdentities,
        SemanticId,
        SelectedTypedRow<LoweredIntrinsicSeed>
    );
    counted_typed_pages!(
        visit_binding_projection_pages_for_references,
        VisitBindingProjectionPagesForReferences,
        SemanticId,
        SelectedTypedRow<LoweredBindingProjection>
    );
    counted_typed_pages!(
        visit_binding_projection_pages_for_outputs,
        VisitBindingProjectionPagesForOutputs,
        SemanticId,
        SelectedTypedRow<LoweredBindingProjection>
    );
    counted_typed_pages!(
        visit_qualified_route_pages_for_references,
        VisitQualifiedRoutePagesForReferences,
        SemanticId,
        SelectedQualifiedRoute
    );
    counted_typed_pages!(
        visit_qualified_route_pages_for_slot_lookups,
        VisitQualifiedRoutePagesForSlotLookups,
        QualifiedRouteSlotLookup,
        SelectedQualifiedRoute
    );
    counted_typed_pages!(
        visit_qualified_route_pages_for_qualifier_slots,
        VisitQualifiedRoutePagesForQualifierSlots,
        SemanticId,
        SelectedQualifiedRoute
    );
    counted_typed_pages!(
        visit_qualified_route_pages_for_lookups,
        VisitQualifiedRoutePagesForLookups,
        SemanticId,
        SelectedQualifiedRoute
    );
    counted_typed_pages!(
        visit_qualified_route_pages_for_gap_reasons,
        VisitQualifiedRoutePagesForGapReasons,
        SemanticId,
        SelectedQualifiedRoute
    );

    counted_typed_inventory!(
        visit_qualified_route_inventory_pages,
        VisitQualifiedRouteInventoryPages,
        SelectedQualifiedRoute
    );

    counted_typed_pages!(
        visit_declaration_type_pages_for_definitions,
        VisitDeclarationTypePagesForDefinitions,
        SemanticId,
        SelectedTypedRow<LoweredDeclarationTypeProperty>
    );
    counted_typed_pages!(
        visit_declaration_type_pages_for_slots,
        VisitDeclarationTypePagesForSlots,
        SemanticId,
        SelectedTypedRow<LoweredDeclarationTypeProperty>
    );
    counted_typed_pages!(
        visit_declaration_visibility_pages_for_definitions,
        VisitDeclarationVisibilityPagesForDefinitions,
        SemanticId,
        SelectedTypedRow<LoweredDeclarationVisibilityProperty>
    );
    counted_typed_pages!(
        visit_member_scope_pages_for_definitions,
        VisitMemberScopePagesForDefinitions,
        SemanticId,
        SelectedTypedRow<LoweredMemberScopeProperty>
    );
    counted_typed_pages!(
        visit_member_scope_pages_for_heads,
        VisitMemberScopePagesForHeads,
        BindingNodeId,
        SelectedTypedRow<LoweredMemberScopeProperty>
    );
    counted_typed_pages!(
        visit_member_owner_pages_for_definitions,
        VisitMemberOwnerPagesForDefinitions,
        SemanticId,
        SelectedTypedRow<LoweredMemberOwnerProperty>
    );
    counted_typed_pages!(
        visit_member_owner_pages_for_owners,
        VisitMemberOwnerPagesForOwners,
        SemanticId,
        SelectedTypedRow<LoweredMemberOwnerProperty>
    );
    counted_typed_pages!(
        visit_deferred_member_owner_pages_for_definitions,
        VisitDeferredMemberOwnerPagesForDefinitions,
        SemanticId,
        SelectedTypedRow<LoweredDeferredMemberOwner>
    );
    counted_typed_pages!(
        visit_deferred_member_owner_pages_for_lookup_names,
        VisitDeferredMemberOwnerPagesForLookupNames,
        DeferredMemberOwnerLookupName,
        SelectedTypedRow<LoweredDeferredMemberOwner>
    );
    counted_typed_pages!(
        visit_construction_requirement_pages_for_definitions,
        VisitConstructionRequirementPagesForDefinitions,
        SemanticId,
        SelectedTypedRow<LoweredConstructionRequirementProperty>
    );
    counted_typed_pages!(
        visit_supertype_pages_for_definitions,
        VisitSupertypePagesForDefinitions,
        SemanticId,
        SelectedTypedRow<LoweredSupertypeProperty>
    );
    counted_typed_pages!(
        visit_supertype_pages_for_references,
        VisitSupertypePagesForReferences,
        SemanticId,
        SelectedTypedRow<LoweredSupertypeProperty>
    );
    counted_typed_pages!(
        visit_supertype_pages_for_frontiers,
        VisitSupertypePagesForFrontiers,
        SemanticId,
        SelectedTypedRow<LoweredSupertypeProperty>
    );
    counted_typed_pages!(
        visit_definition_property_gap_pages_for_definitions,
        VisitDefinitionPropertyGapPagesForDefinitions,
        SemanticId,
        SelectedTypedRow<LoweredDefinitionPropertyGap>
    );
    counted_typed_pages!(
        visit_definition_property_gap_pages_for_reasons,
        VisitDefinitionPropertyGapPagesForReasons,
        SemanticId,
        SelectedTypedRow<LoweredDefinitionPropertyGap>
    );
    counted_typed_pages!(
        visit_call_applicability_pages_for_callee_references,
        VisitCallApplicabilityPagesForCalleeReferences,
        SemanticId,
        SelectedTypedRow<LoweredCallApplicabilityObligation>
    );
    counted_typed_pages!(
        visit_call_applicability_pages_for_gap_reasons,
        VisitCallApplicabilityPagesForGapReasons,
        SemanticId,
        SelectedTypedRow<LoweredCallApplicabilityObligation>
    );
    counted_typed_pages!(
        visit_callable_signature_pages_for_definitions,
        VisitCallableSignaturePagesForDefinitions,
        SemanticId,
        SelectedTypedRow<LoweredCallableSignatureProperty>
    );
    counted_typed_pages!(
        visit_gap_reason_provenance_pages_for_reasons,
        VisitGapReasonProvenancePagesForReasons,
        SemanticId,
        SelectedGapReasonProvenance
    );
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Method names declared at the top level of one trait body.
    ///
    /// This reads the trait's own source so that a method added to either trait
    /// without a forwarding arm in [`SeamProfiled`] fails a test instead of
    /// silently bypassing the decorator. A required method that is not
    /// forwarded fails to compile; a *defaulted* one does not, and its default
    /// body would then run on the decorator and call back into the decorator,
    /// which both miscounts and changes which implementation runs.
    fn declared_methods(source: &str, name: &str) -> Vec<String> {
        let header = format!("pub trait {name} {{");
        let start = source
            .find(&header)
            .unwrap_or_else(|| panic!("trait {name} not found in its own source"))
            + header.len();
        // rustfmt closes a top-level item at column zero, and everything inside
        // a trait body, including a default method's closing brace, is
        // indented. So the first line that is exactly `}` ends the trait.
        // `str::lines` handles both LF and CRLF checkouts.
        let mut methods = Vec::new();
        let mut ended = false;
        for line in source[start..].lines() {
            if line == "}" {
                ended = true;
                break;
            }
            // Four spaces exactly: a method of this trait, never a nested item
            // inside a default body.
            if let Some(rest) = line.strip_prefix("    fn ") {
                let end = rest
                    .find(['(', '<'])
                    .expect("a trait method declaration names its parameters");
                methods.push(rest[..end].to_string());
            }
        }
        assert!(ended, "trait {name} body is unterminated");
        methods
    }

    #[test]
    fn the_decorator_forwards_every_method_of_both_reader_traits() {
        let batch_source = include_str!("batch.rs");
        let batch = declared_methods(batch_source, "BatchResolutionFragmentSource");
        let batch_crlf = batch_source.replace("\r\n", "\n").replace('\n', "\r\n");
        assert_eq!(
            declared_methods(&batch_crlf, "BatchResolutionFragmentSource"),
            batch
        );
        let typed_source = include_str!("fact_source.rs");
        let typed = declared_methods(typed_source, "SelectedTypedFactSource");
        let typed_crlf = typed_source.replace("\r\n", "\n").replace('\n', "\r\n");
        assert_eq!(
            declared_methods(&typed_crlf, "SelectedTypedFactSource"),
            typed
        );
        assert_eq!(batch.len(), 25, "BatchResolutionFragmentSource: {batch:?}");
        assert_eq!(typed.len(), 55, "SelectedTypedFactSource: {typed:?}");

        let forwarded = SeamMethod::ALL
            .iter()
            .map(|method| (method.as_str(), method.owner()))
            .collect::<std::collections::BTreeSet<_>>();
        let declared = batch
            .iter()
            .map(|name| (name.as_str(), "BatchResolutionFragmentSource"))
            .chain(
                typed
                    .iter()
                    .map(|name| (name.as_str(), "SelectedTypedFactSource")),
            )
            .collect::<std::collections::BTreeSet<_>>();
        assert_eq!(
            declared, forwarded,
            "the reader seam and SeamProfiled disagree; declared {declared:?}, forwarded {forwarded:?}"
        );
        assert_eq!(METHOD_COUNT, 80);
    }

    /// The instrument is off unless the variable names a file, and nothing in
    /// this process set it.
    #[test]
    fn the_instrument_is_off_without_its_variable() {
        assert!(
            std::env::var_os(PROFILE_PATH_ENV).is_none(),
            "{PROFILE_PATH_ENV} must be unset for the library test suite"
        );
        assert!(!enabled());
        record_call(SeamMethod::ReferenceSeed, 7);
        record_rows(SeamMethod::ReferenceSeed, 7);
        assert!(PROFILE.get().expect("read once above").is_none());
    }
}
