#!/usr/bin/env python3
"""Canonicalize and verify the SQLite cache baseline and later migrations.

The baseline is hand-authored SQL. SQLite stores each object's text verbatim
from `CREATE` onward, so `sqlite_master` can confirm what the file declares but
cannot reproduce the file: it keeps no comment written above a `CREATE`, and it
reports objects in its own order rather than the author's. Rendering the file
out of `sqlite_master` therefore deleted every explanatory comment above a
statement and moved statements around, which is why the baseline was edited by
hand instead of regenerated.

The division of ownership follows from that. The author owns the schema
statements and their order; SQLite already preserves their text exactly, so a
generator has nothing to canonicalize in them. The generator owns the seed
rows, which are data and have a canonical rendering. Both are checked against
the database the file builds:

  * every `CREATE` in the file is one object in `sqlite_master`, and every
    object in `sqlite_master` is one `CREATE` in the file, matched on exact
    text, so the file can neither drop an object nor declare one SQLite does
    not build;
  * the file's `INSERT` statements are exactly the canonical rendering of the
    seed rows;
  * the baseline and the migration chain apply, satisfy their foreign keys and
    pass `integrity_check`.

Statement order belongs to the author, and applying the file proves it valid:
SQLite rejects an index or a trigger whose table does not exist yet.
"""

from __future__ import annotations

import argparse
import math
import re
import sqlite3
import sys
from pathlib import Path
from typing import NamedTuple, Sequence


CURRENT_MIGRATION_VERSION = 138
BASELINE_MIGRATION_VERSION = 125
MIGRATION_VERSIONS = tuple(
    range(BASELINE_MIGRATION_VERSION, CURRENT_MIGRATION_VERSION + 1)
)
MIGRATION_FILE_RE = re.compile(r"(?P<version>[0-9]{4})-[^/]+\.sql\Z")
SCHEMA_OBJECT_TYPES = ("table", "index", "view", "trigger")
BASELINE_HEADER = (
    "-- Generated by scripts/public/generate-cache-schema.py.",
    "-- Do not edit manually; regenerate this schema 125 baseline.",
    "-- This is the schema and seed data for a newly created cache store.",
)


def repository_root() -> Path:
    # This file lives at scripts/public/<name>.py.
    return Path(__file__).resolve().parents[2]


def migration_paths(root: Path) -> list[tuple[int, Path]]:
    migration_dir = root / "crates" / "bifrost-core" / "migrations" / "cache"
    by_version: dict[int, Path] = {}
    for path in migration_dir.glob("*.sql"):
        match = MIGRATION_FILE_RE.fullmatch(path.name)
        if match is None:
            continue
        version = int(match.group("version"))
        if version in MIGRATION_VERSIONS:
            if version in by_version:
                raise RuntimeError(f"duplicate cache migration version {version}")
            by_version[version] = path

    missing = [version for version in MIGRATION_VERSIONS if version not in by_version]
    if missing:
        raise RuntimeError(f"missing cache migration files: {missing}")
    return [(version, by_version[version]) for version in MIGRATION_VERSIONS]


def quote_identifier(identifier: str) -> str:
    return '"' + identifier.replace('"', '""') + '"'


def connect_memory() -> sqlite3.Connection:
    connection = sqlite3.connect(":memory:")
    connection.execute("PRAGMA foreign_keys = ON")
    return connection


def apply_baseline_and_migrations(
    connection: sqlite3.Connection, migrations: Sequence[tuple[int, Path]]
) -> None:
    for version, path in migrations:
        connection.executescript(path.read_text(encoding="utf-8"))
        connection.execute(f"PRAGMA user_version = {version}")


def schema_definitions(connection: sqlite3.Connection) -> list[tuple[str, str, str]]:
    return list(
        connection.execute(
            """
            SELECT type, name, sql
            FROM sqlite_master
            WHERE name NOT LIKE 'sqlite_%' AND sql IS NOT NULL
            ORDER BY type, name
            """
        )
    )


class Statement(NamedTuple):
    """One baseline statement with the text written above it.

    `lead` holds the blank lines and comment lines that precede the statement.
    They are the author's and round-trip verbatim; `sqlite_master` keeps no
    record of them.
    """

    lead: list[str]
    lines: list[str]

    @property
    def text(self) -> str:
        return "\n".join(self.lines)

    def keyword(self) -> str:
        return self.text.split(maxsplit=1)[0].upper()

    def rendered(self) -> list[str]:
        return [*self.lead, *self.lines]


def parse_statements(text: str, label: str) -> list[Statement]:
    """Split the baseline into statements, keeping every byte of the file.

    `sqlite3.complete_statement` is SQLite's own scanner, so a semicolon inside
    a trigger body, a string literal or a comment does not end a statement.
    """
    lines = text.split("\n")
    if not lines or lines[-1] != "":
        raise RuntimeError(f"{label} must end with a newline")
    lines.pop()

    statements: list[Statement] = []
    pending: list[str] = []
    for line in lines:
        pending.append(line)
        block = "\n".join(pending)
        if not block.strip() or not sqlite3.complete_statement(block):
            continue
        head = 0
        while head < len(pending) and (
            not pending[head].strip() or pending[head].lstrip().startswith("--")
        ):
            head += 1
        statements.append(Statement(pending[:head], pending[head:]))
        pending = []
    if pending:
        raise RuntimeError(
            f"{label} ends with an incomplete statement: "
            + repr("\n".join(pending)[-200:])
        )
    return statements


def table_columns(connection: sqlite3.Connection, table: str) -> list[str]:
    pragma = f"PRAGMA table_xinfo({quote_identifier(table)})"
    columns = [row[1] for row in connection.execute(pragma) if row[6] == 0]
    if not columns:
        raise RuntimeError(f"table {table!r} has no insertable columns")
    return columns


def value_sort_key(value: object) -> tuple[str, str]:
    if value is None:
        return ("0", "")
    if isinstance(value, bytes):
        return ("1", value.hex())
    if isinstance(value, int):
        return ("2", str(value))
    if isinstance(value, float):
        return ("3", repr(value))
    if isinstance(value, str):
        return ("4", value)
    raise TypeError(f"unsupported SQLite value type {type(value).__name__}")


def table_rows(
    connection: sqlite3.Connection, table: str, columns: Sequence[str]
) -> list[tuple[object, ...]]:
    selected = ", ".join(quote_identifier(column) for column in columns)
    rows = connection.execute(
        f"SELECT {selected} FROM {quote_identifier(table)}"
    ).fetchall()
    rows.sort(key=lambda row: tuple(value_sort_key(value) for value in row))
    return rows


def sql_literal(value: object) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bytes):
        return f"X'{value.hex()}'"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        if not math.isfinite(value):
            raise RuntimeError(f"non-finite seed value {value!r}")
        return repr(value)
    if isinstance(value, str):
        return "'" + value.replace("'", "''") + "'"
    raise TypeError(f"unsupported SQLite value type {type(value).__name__}")


def seed_inserts(connection: sqlite3.Connection) -> list[str]:
    """The canonical `INSERT` rendering of every seeded row, in table order."""
    inserts: list[str] = []
    for object_type, table, _ in schema_definitions(connection):
        if object_type != "table":
            continue
        columns = table_columns(connection, table)
        quoted_columns = ", ".join(quote_identifier(column) for column in columns)
        for row in table_rows(connection, table, columns):
            values = ", ".join(sql_literal(value) for value in row)
            inserts.append(
                f"INSERT INTO {quote_identifier(table)} ({quoted_columns}) "
                f"VALUES ({values});"
            )
    return inserts


def verify_statements(
    connection: sqlite3.Connection, statements: Sequence[Statement], label: str
) -> None:
    """Match the file against the database it builds, in both directions."""
    if not statements:
        raise RuntimeError(f"{label} declares no statements")
    if tuple(statements[0].lead[: len(BASELINE_HEADER)]) != BASELINE_HEADER:
        raise RuntimeError(f"{label} does not start with the generated-file header")

    declared: dict[str, Statement] = {}
    file_inserts: list[str] = []
    for statement in statements:
        keyword = statement.keyword()
        if keyword == "INSERT":
            file_inserts.append(statement.text)
            continue
        if keyword != "CREATE":
            raise RuntimeError(
                f"{label} holds a statement that is neither CREATE nor INSERT: "
                f"{statement.text[:120]!r}"
            )
        body = statement.text.rstrip()
        if not body.endswith(";"):
            raise RuntimeError(
                f"{label} statement is not terminated: {statement.text[:120]!r}"
            )
        body = body[:-1].rstrip()
        if body in declared:
            raise RuntimeError(f"{label} declares one object twice: {body[:120]!r}")
        declared[body] = statement

    built: dict[str, tuple[str, str]] = {}
    for object_type, name, sql in schema_definitions(connection):
        if object_type not in SCHEMA_OBJECT_TYPES:
            raise RuntimeError(
                f"unexpected schema object type {object_type!r} for {name!r}"
            )
        built[sql] = (object_type, name)

    # Both directions are checked by exact text. A name filter that skipped
    # objects is what let an earlier generator delete a live trigger from the
    # baseline; this bijection is what replaces it, and it cannot be outgrown
    # by a naming convention.
    dropped = sorted(built[sql] for sql in built if sql not in declared)
    if dropped:
        raise RuntimeError(f"{label} is missing schema objects SQLite builds: {dropped}")
    invented = sorted(body[:120] for body in declared if body not in built)
    if invented:
        raise RuntimeError(
            f"{label} declares statements SQLite does not report as schema: {invented}"
        )

    expected_inserts = seed_inserts(connection)
    if file_inserts != expected_inserts:
        unexpected = [row[:120] for row in file_inserts if row not in expected_inserts]
        missing = [row[:120] for row in expected_inserts if row not in file_inserts]
        raise RuntimeError(
            f"{label} seed rows are not the canonical rendering; "
            f"unexpected={unexpected}, missing={missing}"
        )


def render_snapshot(
    connection: sqlite3.Connection, statements: Sequence[Statement]
) -> str:
    """Re-emit the baseline: the author's schema text, generated seed rows."""
    canonical = iter(seed_inserts(connection))
    lines: list[str] = []
    for statement in statements:
        if statement.keyword() == "INSERT":
            statement = Statement(statement.lead, [next(canonical)])
        lines.extend(statement.rendered())
    return "\n".join(lines) + "\n"


def validate_database(connection: sqlite3.Connection, label: str) -> None:
    violations = connection.execute("PRAGMA foreign_key_check").fetchall()
    if violations:
        raise RuntimeError(f"{label} leaves foreign-key violations: {violations}")
    if connection.execute("PRAGMA integrity_check").fetchone()[0] != "ok":
        raise RuntimeError(f"{label} failed integrity_check")


def verify_baseline_and_chain(
    canonical_baseline: str, migrations: Sequence[tuple[int, Path]]
) -> None:
    baseline = connect_memory()
    baseline.executescript(canonical_baseline)
    baseline.execute(f"PRAGMA user_version = {BASELINE_MIGRATION_VERSION}")
    validate_database(baseline, "cache baseline")
    verify_statements(
        baseline,
        parse_statements(canonical_baseline, "cache baseline"),
        "cache baseline",
    )

    chain = connect_memory()
    chain.executescript(canonical_baseline)
    chain.execute(f"PRAGMA user_version = {BASELINE_MIGRATION_VERSION}")
    apply_baseline_and_migrations(chain, migrations[1:])
    validate_database(chain, "cache baseline and migration chain")
    version = chain.execute("PRAGMA user_version").fetchone()[0]
    if version != CURRENT_MIGRATION_VERSION:
        raise RuntimeError(
            f"cache migration chain reached version {version}, "
            f"not {CURRENT_MIGRATION_VERSION}"
        )

    if CURRENT_MIGRATION_VERSION == BASELINE_MIGRATION_VERSION:
        if schema_definitions(chain) != schema_definitions(baseline):
            raise RuntimeError("canonical baseline schema differs after reapplication")
        if seed_inserts(chain) != seed_inserts(baseline):
            raise RuntimeError("canonical baseline seed rows differ after reapplication")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the checked-in baseline and later migrations without rewriting it",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="baseline path (defaults to migrations/cache/0125-baseline.sql)",
    )
    args = parser.parse_args()

    root = repository_root()
    output = args.output or root / "crates/bifrost-core/migrations/cache/0125-baseline.sql"
    migrations = migration_paths(root)
    source = migrations[0][1].read_text(encoding="utf-8")
    statements = parse_statements(source, "cache baseline")
    baseline = connect_memory()
    baseline.executescript(source)
    verify_statements(baseline, statements, "cache baseline")
    rendered = render_snapshot(baseline, statements)
    verify_baseline_and_chain(rendered, migrations)

    if args.check:
        checked_in = output.read_text(encoding="utf-8") if output.exists() else None
        if checked_in != rendered:
            print(f"stale cache schema baseline: {output}", file=sys.stderr)
            return 1
        print(f"cache schema baseline and migration chain are current: {output}")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_bytes(rendered.encode("utf-8"))
    print(f"wrote and verified cache schema baseline: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
